<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pass</name>
   <tag></tag>
   <elementGuidId>87fb1f32-df5a-4628-b13d-2e4d8d4ac519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='new-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;new-password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a92db07-354b-4369-a932-e0ecd897339e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>300a4143-7331-426f-ae0f-f8925745d57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control sb-input inp1 ng-touched ng-valid ng-dirty</value>
      <webElementGuid>fa0098fa-caf0-4db3-a5d3-a29e5e945456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>032817e6-36e9-4a48-b9e0-0e4bf6a373ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>be4479e4-dd68-414e-b985-15d6ca3f046f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>08a1aa37-cb13-4dbe-9d77-ba56315c5307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a47546fb-e197-4145-8382-74b653d4752c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu</value>
      <webElementGuid>bd31c5ff-e9df-4013-a130-76d61fe27152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-component&quot;)/kt-auth[1]/div[@class=&quot;bg-container&quot;]/div[@class=&quot;bg-login&quot;]/kt-login[1]/div[@class=&quot;sb-login-custom-form&quot;]/div[@class=&quot;w-100 sb-login-text-form&quot;]/form[@class=&quot;kt-form h-100 ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;form-group m-0&quot;]/div[@class=&quot;d-inline-flex w-100&quot;]/input[@class=&quot;form-control sb-input inp1 ng-touched ng-valid ng-dirty&quot;]</value>
      <webElementGuid>3cf9b7f0-1d21-4260-910d-2814fa66f726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='new-password']</value>
      <webElementGuid>ab861a5c-76ea-49e3-a318-f8b4868c900e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app-component']/kt-auth/div/div[2]/kt-login/div/div[4]/form/div[2]/div/input</value>
      <webElementGuid>9bd99bc3-fe81-4a76-a5d2-9de57d32d4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ada4f59c-2a11-41fe-9ae4-5c9da4ffcd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'new-password' and @type = 'password' and @placeholder = 'Mật khẩu']</value>
      <webElementGuid>9df6a242-a64c-4f6b-b353-421b1e714df0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
