<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_userName</name>
   <tag></tag>
   <elementGuidId>ce9d70b6-8e69-4dd6-8a95-c2bc2531b9ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Thay đổi tài Khoản mặc định'])[2]/preceding::span[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.kt-header__topbar-item.kt-header__topbar-item--user.show.dropdown > div > span.kt-header__topbar-username.kt-hidden-mobile.dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7ba25e0c-4370-48e9-97e0-f89794fd207b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e3308d3-4fe3-4f99-8dd6-8b480e8e394a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt-header__topbar-username kt-hidden-mobile dropdown-toggle</value>
      <webElementGuid>ebd41c8b-a4c7-47af-8706-b3a7c8a97383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>610277ca-1c7b-4cd0-97af-a424f103f55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DINH LE HOANG</value>
      <webElementGuid>36513d8f-f48b-4505-8765-5f54590c02d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_header&quot;)/kt-topbar[1]/div[@class=&quot;kt-header__topbar&quot;]/kt-user-profile[1]/div[@class=&quot;kt-header__topbar-item kt-header__topbar-item--user&quot;]/div[@class=&quot;kt-header__topbar-item kt-header__topbar-item--user show dropdown&quot;]/div[1]/span[@class=&quot;kt-header__topbar-username kt-hidden-mobile dropdown-toggle&quot;]</value>
      <webElementGuid>b7c5468d-abb9-49d8-b84a-0fd7aa9d5fdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_header']/kt-topbar/div/kt-user-profile/div/div[2]/div/span</value>
      <webElementGuid>f615c297-2f64-44fb-9520-d61e29f66679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem ảnh đại diện'])[2]/following::span[1]</value>
      <webElementGuid>ba637f60-d299-477f-aaab-b35386aeefd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='account_circle'])[2]/following::span[1]</value>
      <webElementGuid>c1ed1d4c-dcea-4728-bee8-81835cf0f318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số dư   * * * * * *'])[2]/preceding::span[2]</value>
      <webElementGuid>15021d8b-ba05-4bc3-bcde-be7077abfb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thay đổi tài Khoản mặc định'])[2]/preceding::span[5]</value>
      <webElementGuid>4d2790ac-a85a-497a-a2d9-1b934ccb0269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kt-header/div/kt-topbar/div/kt-user-profile/div/div[2]/div/span</value>
      <webElementGuid>77766dd2-da72-4f20-9fe3-1d6caadbb562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'DINH LE HOANG' or . = 'DINH LE HOANG')]</value>
      <webElementGuid>7e8662f7-b731-4c21-b66f-27635e9acee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
