<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Qun mt khu_w-100 sb-login-text-form</name>
   <tag></tag>
   <elementGuidId>f75351b2-b4c6-4582-9537-609dee7d3436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='app-component']/kt-auth/div/div[2]/kt-login/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.w-100.sb-login-text-form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba311053-a0ee-45b9-bf41-2ce4b8f706bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 sb-login-text-form</value>
      <webElementGuid>0b608a4e-0731-4b9f-a1d6-31db4f3aca9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-component&quot;)/kt-auth[1]/div[@class=&quot;bg-container&quot;]/div[@class=&quot;bg-login&quot;]/kt-login[1]/div[@class=&quot;sb-login-custom-form&quot;]/div[@class=&quot;w-100 sb-login-text-form&quot;]</value>
      <webElementGuid>399b91f4-528c-4096-98ec-9d56c82c3b67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app-component']/kt-auth/div/div[2]/kt-login/div/div[4]</value>
      <webElementGuid>4d985e5e-4608-4868-a5b4-62d328c5b76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quên mật khẩu?'])[1]/preceding::div[5]</value>
      <webElementGuid>a288b724-6a30-4ffd-9c2d-ad748aba59bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[1]/preceding::div[7]</value>
      <webElementGuid>820a78f4-81a1-4c35-8a2f-3abeee217247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kt-login/div/div[4]</value>
      <webElementGuid>1cad25f9-59b4-49b5-a04b-6bd6519a4c18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
