<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qun mt khu_username</name>
   <tag></tag>
   <elementGuidId>c845381e-8bf8-4b08-8d0e-228dc2600e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad1f42e4-4ee1-4026-9c02-50a6ae3f984a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>deb0c3ec-16e7-4221-b35e-a088f8ce536f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control sb-input inp1 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6dbd9b8a-1a94-4f59-a1c2-877e6705fe1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>f392a385-05b5-4ace-817e-a2a91bc300bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>be6d9b8d-76b5-4895-b7b9-136373697ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>d1edf743-79b0-47f6-a63d-b3352f338c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea5e2e8e-275f-4bd5-acb9-57f557d159ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tên đăng nhập</value>
      <webElementGuid>39bf3670-f31d-46e0-89d7-2b54f37e3f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-component&quot;)/kt-auth[1]/div[@class=&quot;bg-container&quot;]/div[@class=&quot;bg-login&quot;]/kt-login[1]/div[@class=&quot;sb-login-custom-form&quot;]/div[@class=&quot;w-100 sb-login-text-form&quot;]/form[@class=&quot;kt-form h-100 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-group m-0&quot;]/div[@class=&quot;d-inline-flex w-100&quot;]/input[@class=&quot;form-control sb-input inp1 ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>ce8e5da4-0e34-41da-935f-074f4d1298e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>f1a99a54-a4cb-4b38-bd15-010ef8f4f5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app-component']/kt-auth/div/div[2]/kt-login/div/div[4]/form/div/div/input</value>
      <webElementGuid>c97d50d5-6952-48a4-ba98-ce24f9cc1e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d9961be8-36ff-463e-97bd-3cfb485b9e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @type = 'text' and @placeholder = 'Tên đăng nhập']</value>
      <webElementGuid>c7d01e22-6503-4d84-9c3e-d82604bbe16d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
