<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qun mt khu_new-password</name>
   <tag></tag>
   <elementGuidId>381f02be-43dc-4c46-b249-313a86d4640c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='new-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;new-password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab90fefd-5a6c-4dc4-ae46-72288f948321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>52bcda0c-8bb2-49fd-95d2-16e045c8290b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control sb-input inp1 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>e0e39837-829a-470b-85a5-8d52a5eec860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>32f0aec0-24d5-4566-926c-1c8ab03dc838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>10deecb1-3f4a-47be-b785-d363eb5b2587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>3a5c941e-7ba6-4877-8303-04d88477eb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0705c25b-8cd4-4f4d-96c7-be7670fb22d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu</value>
      <webElementGuid>d83798f5-5858-4b97-8716-8d223e4d5eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-component&quot;)/kt-auth[1]/div[@class=&quot;bg-container&quot;]/div[@class=&quot;bg-login&quot;]/kt-login[1]/div[@class=&quot;sb-login-custom-form&quot;]/div[@class=&quot;w-100 sb-login-text-form&quot;]/form[@class=&quot;kt-form h-100 ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;form-group m-0&quot;]/div[@class=&quot;d-inline-flex w-100&quot;]/input[@class=&quot;form-control sb-input inp1 ng-untouched ng-valid ng-dirty&quot;]</value>
      <webElementGuid>09244a8d-db4a-4025-a07d-0bf2f89e1475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='new-password']</value>
      <webElementGuid>192195f6-fb92-4952-9ad3-b0a8f299837b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app-component']/kt-auth/div/div[2]/kt-login/div/div[4]/form/div[2]/div/input</value>
      <webElementGuid>4f225ef6-1056-4863-963b-73f2e64552bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c4196d29-460c-4150-ac10-dd4e06919da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'new-password' and @type = 'password' and @placeholder = 'Mật khẩu']</value>
      <webElementGuid>29215788-01a5-41cb-a8c3-ead27d632d50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
